head	1.2;
access;
symbols;
locks; strict;
comment	@# @;


1.2
date	2016.06.03.11.42.30;	author sthen;	state dead;
branches;
next	1.1;
commitid	HxYXkUiSZrdtSQv2;

1.1
date	2016.05.27.10.01.38;	author sthen;	state Exp;
branches;
next	;
commitid	RiApEODvCemtbdir;


desc
@@


1.2
log
@update to certbot-0.7.0 (another one that would have been earlier if the
pypi.io redirector actually worked properly)
@
text
@$OpenBSD: patch-certbot_plugins_webroot_py,v 1.1 2016/05/27 10:01:38 sthen Exp $

https://github.com/letsencrypt/letsencrypt/pull/2788
(will be fixed differently in 0.7.0)

--- certbot/plugins/webroot.py.orig	Fri May 27 10:44:22 2016
+++ certbot/plugins/webroot.py	Fri May 27 10:44:31 2016
@@@@ -181,7 +181,7 @@@@ to serve all files under specified web root ({0})."""
                     os.chown(self.full_roots[name], stat_path.st_uid,
                              stat_path.st_gid)
                 except OSError as exception:
-                    if exception.errno == errno.EACCES:
+                    if exception.errno == errno.EACCES or exception.errno == errno.EPERM:
                         logger.debug("Insufficient permissions to change owner and uid - ignoring")
                     else:
                         raise errors.PluginError(
@


1.1
log
@update letsencrypt/client to 0.6.0, and cope with the renaming to "certbot".
courtesy symlink provided so that scripts still work.
@
text
@d1 1
a1 1
$OpenBSD$
@

