head	1.2;
access;
symbols;
locks; strict;
comment	@# @;


1.2
date	2017.09.18.12.12.46;	author landry;	state dead;
branches;
next	1.1;
commitid	qhP7WG7LMpF25Zop;

1.1
date	2017.07.19.15.48.31;	author zhuk;	state Exp;
branches;
next	;
commitid	qG5K0eesrInfF0kW;


desc
@@


1.2
log
@Update to QGIS 2.18.13.

Remove python/core/qgscoordinatetransform.sip patch, was fixed
differently upstream in https://issues.qgis.org/issues/17039
@
text
@$OpenBSD: patch-python_core_qgscoordinatetransform_sip,v 1.1 2017/07/19 15:48:31 zhuk Exp $
Fix build with py-sip-4.19.3.

Idea taken from Arch Linux, see https://aur.archlinux.org/packages/qgis/

Index: python/core/qgscoordinatetransform.sip
--- python/core/qgscoordinatetransform.sip.orig
+++ python/core/qgscoordinatetransform.sip
@@@@ -15,7 +15,6 @@@@
 class QgsCoordinateTransform : QObject
 {
 %TypeHeaderCode
-extern PyObject *sipExportedExceptions__core[2];  // workaround: sipExportedExceptions__core is only defined in the first sip part
 #include <qgscoordinatetransform.h>
 %End
 
@


1.1
log
@Fix situatuion when both new QGis and new SIP are met.

Reported by naddy@@, thanks!
@
text
@d1 1
a1 1
$OpenBSD$
@

